export default {
	id: "",
	role_id: "",
	name: "",
	top_braiders: "",
	email: "",
	dob: "",
	avatar: "",
	gender: "",
	ratting: "",
	address: "",
	state: "",
	city: "",
	zipcode: "",
	country: "",
	business_name: "",
	website_link: "",
	business_phone_number: "",
	phone_number: "",
	introduction: "",
	special_introduction: "",
	policy_procedure: "",
	booking_deposit_amount: "",
	coupon_code: "",
	do_you_braid_out_of_a_shop: "",
	do_you_braid_from_home: "",
	are_you_a_mobile: "",
	can_you_provide_hair: "",
	do_you_wash_hair: "",
	status: "",
	api_token: "",
	completed_stripe_onboarding: "",
	is_payment_online: "",
	stripe_connect_id:"",
	created_at: "",
	updated_at: "",
	calender_url: "",
}
